
POST http://192.168.1.4:8000/api/create-supervisor HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "first_name": "Amdjed",
    "last_name": "Super admin",
    "username": "zamdjseddz_super_admin3",
    "email": "zamdjdedz3ssss@gmail.com",
    "password": "123456789",
    "sexe": "M",
    "phone_number": "0123456789",
    "address": "123 Main St"
}



###
POST http://192.168.1.4:8000/api/create-supervisor HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "first_name": "Amdjed",
    "last_name": "Super admin",
    "username": "amdjsed_super_admin3",
    "email": "amdjeds3@gmail.com",
    "password": "123456789",
    "password_confirmation": "123456789",
    "sexe": "M",
    "phone_number": "0123456789",
    "address": "123 Main St"
}


###

# POST http://192.168.1.4:8000/api/login HTTP/1.1
POST http://127.0.0.1:8000/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "login": "amdjed123",
    "password": "123456789",
    "deviceName": "Desktop"
}


### 
GET  http://127.0.0.1:8000/api/profile HTTP/1.1
# GET  http://192.168.1.4:8000/api/profile HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 300|1Dn6tEKUE37rqghQgYmI9zb5Jp9hN4cpSfeAefWZa38c8f06


{

}