POST http://127.0.0.1:8000/api/create-supervisor HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "first_name": "Amdjed",
    "last_name": "admin2",
    "username": "amdjed_admin2",
    "email": "amdjed_admin2@gmail.com",
    "password": "123456789",
    "password_confirmation": "123456789",
    "sexe": "M",
    "phone_number": "0123456789",
    "address": "123 Main St",
    "role_id": 2
}


###

POST http://127.0.0.1:8000/api/sanctum/token HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "amdjed_admin2@gmail.com",
    "password": "123456789",
    "device_name": "Desktop"
}


### 
GET  http://127.0.0.1:8000/api/profile HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 5|UFLOr45JHGX2RLF9BNP1XVBQS6DMTt7bYxKgJ7Ae9ad07e65

{

}