# Authorization: Bearer 1|1EPMcmEh4EXmDGtamfF0N6NHTkHn8WZmuao17hJ64f2b493f
###
# GET  http://127.0.0.1:8000/api/students HTTP/1.1
GET  http://192.168.139.56:8000/api/students HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|kTOva80mnP2MERl4qeIjMdDzjPhEYYj3Cbyuyzc6eac6d377

{
}

###
GET  http://127.0.0.1:8000/api/gradeinfo/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|FWGZNc0TnKjhaQDLcdRsI0r40qHR9ox943T4Cc2r6cfd574b

{
}

# Authorization: Bearer 1|1EPMcmEh4EXmDGtamfF0N6NHTkHn8WZmuao17hJ64f2b493f
###
POST  http://127.0.0.1:8000/api/student/create HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|kTOva80mnP2MERl4qeIjMdDzjPhEYYj3Cbyuyzc6eac6d377

{
    "first_name": "Amdjed",
    "last_name": "Mrah",
    "section_id": 1,
    "sexe" : "M",
    "student_state_id": 1,
    "student_type_id": 1
}

###
POST  http://127.0.0.1:8000/api/student/code-regenerate/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|FWGZNc0TnKjhaQDLcdRsI0r40qHR9ox943T4Cc2r6cfd574b

{
}


###

GET  http://127.0.0.1:8000/api/assignment/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|FWGZNc0TnKjhaQDLcdRsI0r40qHR9ox943T4Cc2r6cfd574b

{
}


###

GET  http://192.168.139.56:8000/api/student/141 HTTP/1.1
# GET  http://127.0.0.1:8000/api/student/141 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|kTOva80mnP2MERl4qeIjMdDzjPhEYYj3Cbyuyzc6eac6d377


 
{
}

###

GET  http://127.0.0.1:8000/api/deleted HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|zKDFdJ5gtAKnlAZyl1N2wckTLsU8b3mDxdJLzXRaccf7c049


 
{
}


###

DELETE   http://127.0.0.1:8000/api/student/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|zKDFdJ5gtAKnlAZyl1N2wckTLsU8b3mDxdJLzXRaccf7c049


 
{
}