# Authorization: Bearer 1|1EPMcmEh4EXmDGtamfF0N6NHTkHn8WZmuao17hJ64f2b493f
###
POST  http://127.0.0.1:8000/api/create-student HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|lGDqmE4Xn7qkXCD7OM82tz9ovKgyIo5rEzi0xkWJ34ecc8bd

{
    "first_name": "Amdjed",
    "last_name": "Mrah2",
    "class": "10B",
    "code": "2A",
    "student_state_id": 1,
    "student_type_id": 1
}


###

GET  http://127.0.0.1:8000/api/students HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|lGDqmE4Xn7qkXCD7OM82tz9ovKgyIo5rEzi0xkWJ34ecc8bd

{
}


###

GET  http://127.0.0.1:8000/api/student/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|lGDqmE4Xn7qkXCD7OM82tz9ovKgyIo5rEzi0xkWJ34ecc8bd


 
{
}

###

GET  http://127.0.0.1:8000/api/deleted HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|lGDqmE4Xn7qkXCD7OM82tz9ovKgyIo5rEzi0xkWJ34ecc8bd


 
{
}


###

DELETE   http://127.0.0.1:8000/api/student/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|lGDqmE4Xn7qkXCD7OM82tz9ovKgyIo5rEzi0xkWJ34ecc8bd


 
{
}